esphome:
  name: garage-door-sonoff
  friendly_name: garage-door-sonoff

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXXXXXXXXXXXXXXX"

ota:
  - platform: esphome
    password: "XXXXXXXXXXXXXXXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-Door-Sonoff"
    password: "XXXXXXXXXXXXXXXXXXX"

captive_portal:

binary_sensor:
  - platform: gpio
    internal: True
    name: Door Button
    id: button_physical
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay2
  - platform: gpio
    name: Door State
    pin: GPIO03
    device_class: garage_door
    id: reed

button:
  - platform: template
    internal: False
    name: Roller Door Button
    id: button_1
    on_press: 
      - switch.turn_on: relay2

switch:
  - platform: gpio
    name: Lights
    pin: GPIO12
    id: relay1
    icon: mdi:lightbulb-fluorescent-tube-outline
  - platform: gpio
    name: Roller Door
#   pin: GPIO14
    pin:
      number: GPIO14
      inverted: False
#   restore_mode: DISABLED
    restore_mode: RESTORE_DEFAULT_OFF
    id: relay2
    on_turn_on: 
      - delay: 500ms
      - switch.turn_off: relay2

                

#  - platform: template
#    name: "Garage Door Button"
#    id: garage_door_button
#    restore_mode: DISABLED
#    turn_on_action:
#      - switch.turn_on: relay2
#      - delay: 500ms
#      - switch.turn_off: relay2
#    turn_off_action:
#      - switch.turn_on: relay2
#      - delay: 500ms
#      - switch.turn_off: relay2

status_led:
  pin:
    number: GPIO13
    inverted: yes
    
sensor:
  - platform: wifi_signal
    name: "Lamp 1 WiFi Sensor"
    update_interval: 60s
  - platform: dht
    pin: GPIO04
    temperature:
      name: Garage temperature
    humidity: 
      name: Garage humidity
    update_interval: 60s
  - platform: uptime
    type: seconds
    name: Uptime Sensor
    update_interval: 60s
    

time:
  - platform: sntp
    
